spring:
  application:
    name: ketari
  datasource:
    url: jdbc:mysql://localhost:3406/ketari_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    clean-disabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME:default}
    password: ${MAIL_PASSWORD:default}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Application Settings
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-expiration: 86400000 # 24 hours in milliseconds
    refresh-expiration: 604800000 # 7 days in milliseconds
  storage:
    resume-dir: uploads/resumes
